### ISSUE TITLE
Zip code recognition is wrong

### ISSUE THREAD

**Issue by jj20466** [NatTupper/Forecast#3]
I put my zip code in which is 6108 in the app but it says i live in east hartford,us when i live in thornlie,aus

**Comment by DevShadd** [comment]
I'm pretty sure that it only recognizes US ZIP codes. The East Hartford zip code is 06108. Maybe he'll change this in the future.

**Comment by NatTupper** [comment]
Sorry, support is only for US zip codes right now but it does support geographic coordinates.
